### ISSUE TITLE
How catch IllegalArgumentsException

### ISSUE THREAD

**Issue by dkonurov** [BottleRocketStudios/Android-Barcode#1]
`FATAL EXCEPTION: AsyncTask #1
                                                   Process: com.example.dmitry.test, PID: 26891
                                                   java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                       at java.lang.Thread.run(Thread.java:761)
                                                    Caused by: java.lang.IllegalArgumentException: Requested contents should be 13 digits long, but got 8
                                                       at com.google.zxing.oned.EAN13Writer.encode(EAN13Writer.java:57)
                                                       at com.google.zxing.oned.OneDimensionalCodeWriter.encode(OneDimensionalCodeWriter.java:70)
                                                       at com.google.zxing.oned.EAN13Writer.encode(EAN13Writer.java:50)
                                                       at com.google.zxing.MultiFormatWriter.encode(MultiFormatWriter.java:94)
                                                       at com.bottlerocketstudios.barcode.generation.controller.BarcodeBitmapGenerator.generate(BarcodeBitmapGenerator.java:39)
                                                       at com.bottlerocketstudios.barcode.generation.controller.AsyncBarcodeBitmapGenerator$BarcodeGenerationTask.doInBackground(AsyncBarcodeBitmapGenerator.java:53)
                                                       at com.bottlerocketstudios.barcode.generation.controller.AsyncBarcodeBitmapGenerator$BarcodeGenerationTask.doInBackground(AsyncBarcodeBitmapGenerator.java:43)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                       at java.lang.Thread.run(Thread.java:761) `
How catch this exception if i set not correct arguments?

**Comment by plugie** [comment]
I have the same issue. Is there any why to check character ?

**Comment by harishrpatel** [comment]
This repo is deprecated.
